### ISSUE TITLE
Discuss for "Android Testing with Kotlin"

### ISSUE THREAD

**Issue by Jacksgong** [android10/Android-KotlinInTests#1]
Thanks for your [great post](http://fernandocejas.com/2017/02/03/android-testing-with-kotlin/).

I want to comment the comment under the post directly, but there is no available account for me and no way to register either, so I create this issue in here, please forgive me.

---

### How do you deal with the case of mocking the `static` class

I know since `mockito` v2.1.0, it has been supported mock the `final` class or field, what is very friend with the kotlin( I check out the `mockito-kotlin`, it dependencies the `mockito` v2.6.5), but `mockito` doesn't support mocking the `static` class.

Since the `powermock` doesn't compat the `mockito` v2.1.0 yet, because of the refactor of `mockito` v2.1.0, so mocking the `static` class become very inconveniently. How do you deal with this problem, is there any recommended way to solve this problem? Thanks.

**Comment by android10** [comment]
@Jacksgong no apologies! This is actually the best place to have discussions.

I have got a question then...why do you want to test or mock a static class? Can you give more details on that? 

When I see that I cannot mock collaborators, I prefer to think that there is a problem with my code and not with the mocking framework...that is why I want to understand your use case.

**Comment by Jacksgong** [comment]
Thanks for your response, that is why Powermock support mock `static` class or method.

One normal case I have occurred is I write a unit test for `NetworkEngine` and all real network operations is warped in the `NetworkUtil`. Such as:

### `NetworkEngine`:

```java
class NetworkEngine {

...
  @Override
  public boolean upload(byte[] bytes) {
      final StamperConfig config = Stamper.get().getConfig();
      if (!config.isReady()) {
          StamperDebug.d(NetworkEngine.class, "require to upload bytes[%d], but config not ready yet",
                  bytes.length);
          return false;
      }

      final String url = config.getRequestUrl();
      // upload to backend
      final int status = NetworkUtil.post(url, bytes);
      final boolean success = status >= 200 && status < 300;

      if (!success) {
          final String errorUrl = String.format(Locale.ENGLISH,
                  "%s?app_name=%s&uid=%s&status=%d&app_version=%s",
                  config.getErrorReportUrl(),
                  config.getAppName(),
                  config.getUserId(),
                  status,
                  mVersionCode);

          NetworkUtil.getIgnoreResponse(errorUrl, config.getUserAgent());
          StamperDebug.d(NetworkEngine.class, "failed upload bytes[%d], upload to error server, %d",
                  bytes.length, status);
      } else {
          StamperDebug.d(NetworkEngine.class, "success upload bytes[%d]", bytes.length);
      }

      return success;
  }

...
}
```

### `NetworkEngineTest`:

and my unit test for `NetworkEngine#upload` need to mock the `NetworkUtil` class which is the `static` class:

```java
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.assertFalse;
import static org.mockito.Matchers.anyString;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.when;
import static org.powermock.api.mockito.PowerMockito.mockStatic;
import static org.powermock.api.mockito.PowerMockito.verifyStatic;

/**
 * Created by Jacksgong on 18/10/2016.
 */
@RunWith(PowerMockRunner.class)
@PrepareForTest(NetworkUtil.class)
public class NetworkEngineImplTest {

    private NetworkEngine mNetworkEngine;
    private final static byte[] MOCK_BYTES = "mock-bytes".getBytes();

    @BeforeClass
    public static void setUpClass() {
        StamperMocksHelper.mockStamperWithEmptyConfig();
    }

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        mockStatic(NetworkUtil.class);
        mNetworkEngine = new NetworkEngineImpl();
    }

    @After
    public void tearDown() {
        mNetworkEngine.shutdown();
    }

    @Test
    public void upload_configNotReady_returnFalse() {
        when(getStamperConfig().isReady()).thenReturn(false);

        assertFalse(mNetworkEngine.upload(MOCK_BYTES));

        verifyStatic(times(0));
        NetworkUtil.post(anyString(), anyByteArray());

        verifyStatic(times(0));
        NetworkUtil.getIgnoreResponse(anyString(), anyString());
    }

    @Test
    public void upload_200Response_returnTrue() {
        when(getStamperConfig().isReady()).thenReturn(true);
        when(NetworkUtil.post(Mockito.anyString(), anyByteArray())).thenReturn(200);


        assertThat(mNetworkEngine.upload(MOCK_BYTES)).isTrue();


        verifyStatic();
        NetworkUtil.post(anyString(), anyByteArray());
    }

    @Test
    public void upload_failedResponse_reportToErrorServer() {
        when(getStamperConfig().isReady()).thenReturn(true);
        when(NetworkUtil.post(anyString(), anyByteArray())).thenReturn(500);


        assertFalse(mNetworkEngine.upload(MOCK_BYTES));

        verifyStatic();
        NetworkUtil.post(anyString(), anyByteArray());


        verifyStatic();
        NetworkUtil.getIgnoreResponse(anyString(), anyString());
    }

    private StamperConfig getStamperConfig() {
        return Stamper.get().getConfig();
    }

}
```

**Comment by android10** [comment]
In that case I would not use a static class. I would pass it as a collaborator to your ```NetworkEngine.java``` (and if you want only one instance, just use a singleton). 

Also I might need more context but it looks like your utils does many things. It handles errors for example, which I would extract to an error manager or something like that. 

I do not see many reasons to have a static class here. For strings is fine I would say.

**Comment by Jacksgong** [comment]
Sorry, This is just the sample code snippet for covering what you want, you can not deny there are many other `static` classes like `Util` do, we need to mock it, because we don't want them to affect the function what we are testing for.

And I think it is no neccessary to discuss about whether we need to mock the `static` class and method or not, because even if it is a few cases, That is still a problem we need to face to in our actual programing. We need to simplify such case like **powermock** do(there are many people use powermock to mock `static` method or class), though we really can mock the `static` class or method through the most original way used in Java: wrapper a `non-static` class or method for the `static` one, then mock the `non-static` one.

**Comment by android10** [comment]
> And I think it is no neccessary to discuss about whether we need to mock the static class and method or not, because even if it is a few cases, That is still a problem we need to face to in our actual programing. We need to simplify such case like powermock do(there are many people use powermock to mock static method or class), though we really can mock the static class or method through the most original way used in Java: wrapper a non-static class or method for the static one, then mock the non-static one.

Well, that is the thing...I do not have those problems because I do not need to mock any static methods (and in my opinion when that happens, the problem is in your code, and by the way, powermock is a hack). And if there is any of those static methods in a third-party library I just wrapped them in my own class and pass it as a collaborator.

**Comment by android10** [comment]
With that being said. If you need that functionality, unfortunately I have not found a way yet.

**Comment by Jacksgong** [comment]
Okay, I get your point, actually, I agree your solution really works sometimes when it's the architecture matter. thanks for your advice, thanks anyway.
